const express = require("express");
const authRoutes = require("./auth.routes");
const userRoutes = require("./user.routes");
const lawyerRoutes = require("./lawyer.routes");
const documentRoutes = require("./document.routes");
const verificationRoutes = require("./verification.routes");
const appointmentRoutes = require("./appointment.routes");
const paymentRoutes = require("./payment.routes");
const refundRoutes = require("./refund.routes");
const notificationRoutes = require("./notification.routes");
const chatRoutes = require("./chat.routes");
const adminRoutes = require("./admin.routes");
const reviewRoutes = require("./review.routes");
const supportTicketRoutes = require("./supportTicket.routes");
const blogRoutes = require("./blog.routes");
const faqRoutes = require("./faq.routes");
const testimonialRoutes = require("./testimonial.routes");
const seoRoutes = require("./seo.routes");
const messageTemplateRoutes = require("./messageTemplate.routes");
const serviceRoutes = require("./service.routes");
const leadRoutes = require("./lead.routes");
const mediaRoutes = require("./media.routes");
const backupRoutes = require("./backup.routes");
const adminFeatureRoutes = require("./adminFeature.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/lawyers", lawyerRoutes);
router.use("/documents", documentRoutes);
router.use("/verification", verificationRoutes);
router.use("/appointments", appointmentRoutes);
router.use("/payments", paymentRoutes);
router.use("/refunds", refundRoutes);
router.use("/notifications", notificationRoutes);
router.use("/chat", chatRoutes);
router.use("/admin", adminRoutes);
router.use("/reviews", reviewRoutes);
router.use("/support-tickets", supportTicketRoutes);
router.use("/blog", blogRoutes);
router.use("/faq", faqRoutes);
router.use("/testimonials", testimonialRoutes);
router.use("/seo", seoRoutes);
router.use("/admin/message-templates", messageTemplateRoutes);
router.use("/services", serviceRoutes);
router.use("/leads", leadRoutes);
router.use("/admin/media", mediaRoutes);
router.use("/admin/backups", backupRoutes);
router.use("/admin", adminFeatureRoutes);

module.exports = router;
