import { LegalPage } from "@/components/site/legal-page";

export const metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <LegalPage eyebrow="Legal" title="Privacy Policy" updated="July 2026">
      <h2>1. What we collect</h2>
      <p>
        We collect information you provide directly — name, email, phone
        number, and any documents you upload — along with information
        generated by using the platform, such as appointment history,
        payment records, and messages exchanged through the platform&rsquo;s
        chat.
      </p>

      <h2>2. How documents are stored</h2>
      <p>
        Uploaded documents are stored in a private object storage bucket
        with public access blocked at the infrastructure level. Documents
        are never reachable via a public URL — access is granted only
        through short-lived, signed links generated at the moment they&rsquo;re
        needed, to you and the lawyer assigned to review them.
      </p>

      <h2>3. How we use your information</h2>
      <p>
        Your information is used to operate the platform: matching you with
        lawyers, processing payments, sending appointment and payment
        notifications (by email and, where enabled, WhatsApp), and
        responding to support requests. We do not sell your personal data
        to third parties.
      </p>

      <h2>4. Payment information</h2>
      <p>
        Payments are processed by Razorpay. NyayaSetu never receives or
        stores your card number, CVV, or UPI PIN — only a payment
        confirmation reference is retained for our records.
      </p>

      <h2>5. Data retention</h2>
      <p>
        Account and transaction records are retained as required for legal
        and tax compliance. Deleted documents are marked inaccessible
        immediately and permanently removed from storage on a routine
        retention schedule.
      </p>

      <h2>6. Your rights</h2>
      <p>
        You can request a copy of the personal data we hold about you, ask
        for corrections, or request account deletion by contacting
        support@nyayasetu.example. Some information may be retained where
        required by law (e.g., payment records for tax purposes).
      </p>

      <h2>7. Security</h2>
      <p>
        We use encryption in transit and at rest, role-based access
        controls, and audit logging on sensitive actions. No system is
        perfectly secure, and we encourage using a strong, unique password
        for your account.
      </p>

      <h2>8. Contact</h2>
      <p>Privacy questions can be sent to privacy@nyayasetu.example.</p>
    </LegalPage>
  );
}
